#### In this Code We will Cover
- PySpark Dataframe 
- Reading The Dataset
- Checking the Datatypes of the Column(Schema)
- Selecting Columns And Indexing
- Check Describe option similar to Pandas
- Adding Columns
- Dropping columns
- Renaming Columns

In [62]:


from pyspark.sql import SparkSession

In [63]:
spark=SparkSession.builder.appName('Dataframe').getOrCreate()

In [64]:
spark

In [65]:
## read the dataset
df_pyspark=spark.read.option('header','true').csv('fx_rates_sample.csv',inferSchema=True)

In [66]:
### Check the schema
df_pyspark.printSchema()

root
 |-- timestamp: timestamp (nullable = true)
 |-- base: string (nullable = true)
 |-- USD: double (nullable = true)
 |-- SAR: double (nullable = true)
 |-- YER: double (nullable = true)
 |-- EUR: double (nullable = true)

In [67]:
df_pyspark=spark.read.csv('fx_rates_sample.csv',header=True,inferSchema=True)
df_pyspark.show()

+-------------------+----+---+--------+----------+--------+
|          timestamp|base|USD|     SAR|       YER|     EUR|
+-------------------+----+---+--------+----------+--------+
|2025-09-01 09:00:00| USD|1.0|3.750305|249.969495|0.849856|
|2025-09-01 09:01:00| USD|1.0|3.749265|250.046174|0.851548|
|2025-09-01 09:02:00| USD|1.0|3.750015|250.246139|0.848127|
|2025-09-01 09:03:00| USD|1.0|3.750956|250.034432|0.845882|
|2025-09-01 09:04:00| USD|1.0|3.749005| 250.00943|0.844497|
|2025-09-01 09:05:00| USD|1.0|3.747703|250.305721|0.846689|
|2025-09-01 09:06:00| USD|1.0| 3.74783|250.157004|0.847113|
|2025-09-01 09:07:00| USD|1.0|3.747514|249.992554|0.848264|
|2025-09-01 09:08:00| USD|1.0|3.747497|250.033015|0.846554|
|2025-09-01 09:09:00| USD|1.0|3.746644|250.201892|0.844874|
|2025-09-01 09:10:00| USD|1.0|3.747524|250.204177|0.845546|
|2025-09-01 09:11:00| USD|1.0|3.748301|250.469969|0.845634|
|2025-09-01 09:12:00| USD|1.0|3.748368|250.641328|0.846457|
|2025-09-01 09:13:00| USD|1.0|3.749495|250.809692|0.846175|
|2025-09-01 09:14:00| USD|1.0|3.749962|250.920515|0.846592|
|2025-09-01 09:15:00| USD|1.0|3.749103|251.386046| 0.84683|
|2025-09-01 09:16:00| USD|1.0|3.749472|251.345014|0.847996|
|2025-09-01 09:17:00| USD|1.0|3.748513|250.944309|0.849207|
|2025-09-01 09:18:00| USD|1.0|3.749391| 251.26516|0.846777|
|2025-09-01 09:19:00| USD|1.0|3.749341| 251.17362|0.843406|
+-------------------+----+---+--------+----------+--------+
only showing top 20 rows

In [68]:
### Check the schema
df_pyspark.printSchema()

root
 |-- timestamp: timestamp (nullable = true)
 |-- base: string (nullable = true)
 |-- USD: double (nullable = true)
 |-- SAR: double (nullable = true)
 |-- YER: double (nullable = true)
 |-- EUR: double (nullable = true)

In [69]:
type(df_pyspark)

pyspark.sql.classic.dataframe.DataFrame

In [70]:
df_pyspark.head(3)

[Row(timestamp=datetime.datetime(2025, 9, 1, 9, 0), base='USD', USD=1.0, SAR=3.750305, YER=249.969495, EUR=0.849856),
 Row(timestamp=datetime.datetime(2025, 9, 1, 9, 1), base='USD', USD=1.0, SAR=3.749265, YER=250.046174, EUR=0.851548),
 Row(timestamp=datetime.datetime(2025, 9, 1, 9, 2), base='USD', USD=1.0, SAR=3.750015, YER=250.246139, EUR=0.848127)]

In [71]:
df_pyspark.show()

+-------------------+----+---+--------+----------+--------+
|          timestamp|base|USD|     SAR|       YER|     EUR|
+-------------------+----+---+--------+----------+--------+
|2025-09-01 09:00:00| USD|1.0|3.750305|249.969495|0.849856|
|2025-09-01 09:01:00| USD|1.0|3.749265|250.046174|0.851548|
|2025-09-01 09:02:00| USD|1.0|3.750015|250.246139|0.848127|
|2025-09-01 09:03:00| USD|1.0|3.750956|250.034432|0.845882|
|2025-09-01 09:04:00| USD|1.0|3.749005| 250.00943|0.844497|
|2025-09-01 09:05:00| USD|1.0|3.747703|250.305721|0.846689|
|2025-09-01 09:06:00| USD|1.0| 3.74783|250.157004|0.847113|
|2025-09-01 09:07:00| USD|1.0|3.747514|249.992554|0.848264|
|2025-09-01 09:08:00| USD|1.0|3.747497|250.033015|0.846554|
|2025-09-01 09:09:00| USD|1.0|3.746644|250.201892|0.844874|
|2025-09-01 09:10:00| USD|1.0|3.747524|250.204177|0.845546|
|2025-09-01 09:11:00| USD|1.0|3.748301|250.469969|0.845634|
|2025-09-01 09:12:00| USD|1.0|3.748368|250.641328|0.846457|
|2025-09-01 09:13:00| USD|1.0|3.749495|250.809692|0.846175|
|2025-09-01 09:14:00| USD|1.0|3.749962|250.920515|0.846592|
|2025-09-01 09:15:00| USD|1.0|3.749103|251.386046| 0.84683|
|2025-09-01 09:16:00| USD|1.0|3.749472|251.345014|0.847996|
|2025-09-01 09:17:00| USD|1.0|3.748513|250.944309|0.849207|
|2025-09-01 09:18:00| USD|1.0|3.749391| 251.26516|0.846777|
|2025-09-01 09:19:00| USD|1.0|3.749341| 251.17362|0.843406|
+-------------------+----+---+--------+----------+--------+
only showing top 20 rows

In [72]:
df_pyspark.select('SAR','YER').show()

+--------+----------+
|     SAR|       YER|
+--------+----------+
|3.750305|249.969495|
|3.749265|250.046174|
|3.750015|250.246139|
|3.750956|250.034432|
|3.749005| 250.00943|
|3.747703|250.305721|
| 3.74783|250.157004|
|3.747514|249.992554|
|3.747497|250.033015|
|3.746644|250.201892|
|3.747524|250.204177|
|3.748301|250.469969|
|3.748368|250.641328|
|3.749495|250.809692|
|3.749962|250.920515|
|3.749103|251.386046|
|3.749472|251.345014|
|3.748513|250.944309|
|3.749391| 251.26516|
|3.749341| 251.17362|
+--------+----------+
only showing top 20 rows

In [73]:
df_pyspark['USD']

Column<'USD'>

In [74]:
df_pyspark.dtypes

[('timestamp', 'timestamp'),
 ('base', 'string'),
 ('USD', 'double'),
 ('SAR', 'double'),
 ('YER', 'double'),
 ('EUR', 'double')]

In [75]:
df_pyspark.describe().show()

+-------+----+---+--------------------+------------------+--------------------+
|summary|base|USD|                 SAR|               YER|                 EUR|
+-------+----+---+--------------------+------------------+--------------------+
|  count| 360|360|                 360|               360|                 360|
|   mean|NULL|1.0|   3.744513280555554|248.44922222777782|   0.850883833333333|
| stddev|NULL|0.0|0.004873345411568168|1.5941657977836106|0.006840447097655319|
|    min| USD|1.0|            3.734267|        244.467917|            0.837272|
|    max| USD|1.0|            3.755481|        251.457106|            0.865762|
+-------+----+---+--------------------+------------------+--------------------+

In [76]:
### Adding Columns in data frame
# إضافة عمود جديد يعتمد على قيمة EUR
df_pyspark = df_pyspark.withColumn(
    "EUR_plus_2",
    df_pyspark["EUR"] + 2
)
df_pyspark.show(5)

+-------------------+----+---+--------+----------+--------+----------+
|          timestamp|base|USD|     SAR|       YER|     EUR|EUR_plus_2|
+-------------------+----+---+--------+----------+--------+----------+
|2025-09-01 09:00:00| USD|1.0|3.750305|249.969495|0.849856|  2.849856|
|2025-09-01 09:01:00| USD|1.0|3.749265|250.046174|0.851548|  2.851548|
|2025-09-01 09:02:00| USD|1.0|3.750015|250.246139|0.848127|  2.848127|
|2025-09-01 09:03:00| USD|1.0|3.750956|250.034432|0.845882|  2.845882|
|2025-09-01 09:04:00| USD|1.0|3.749005| 250.00943|0.844497|  2.844497|
+-------------------+----+---+--------+----------+--------+----------+
only showing top 5 rows

In [77]:
df_pyspark.show()

+-------------------+----+---+--------+----------+--------+------------------+
|          timestamp|base|USD|     SAR|       YER|     EUR|        EUR_plus_2|
+-------------------+----+---+--------+----------+--------+------------------+
|2025-09-01 09:00:00| USD|1.0|3.750305|249.969495|0.849856|          2.849856|
|2025-09-01 09:01:00| USD|1.0|3.749265|250.046174|0.851548|          2.851548|
|2025-09-01 09:02:00| USD|1.0|3.750015|250.246139|0.848127|          2.848127|
|2025-09-01 09:03:00| USD|1.0|3.750956|250.034432|0.845882|          2.845882|
|2025-09-01 09:04:00| USD|1.0|3.749005| 250.00943|0.844497|          2.844497|
|2025-09-01 09:05:00| USD|1.0|3.747703|250.305721|0.846689|          2.846689|
|2025-09-01 09:06:00| USD|1.0| 3.74783|250.157004|0.847113|2.8471130000000002|
|2025-09-01 09:07:00| USD|1.0|3.747514|249.992554|0.848264|          2.848264|
|2025-09-01 09:08:00| USD|1.0|3.747497|250.033015|0.846554|2.8465540000000003|
|2025-09-01 09:09:00| USD|1.0|3.746644|250.201892|0.844874|          2.844874|
|2025-09-01 09:10:00| USD|1.0|3.747524|250.204177|0.845546|          2.845546|
|2025-09-01 09:11:00| USD|1.0|3.748301|250.469969|0.845634|          2.845634|
|2025-09-01 09:12:00| USD|1.0|3.748368|250.641328|0.846457|          2.846457|
|2025-09-01 09:13:00| USD|1.0|3.749495|250.809692|0.846175|          2.846175|
|2025-09-01 09:14:00| USD|1.0|3.749962|250.920515|0.846592|2.8465920000000002|
|2025-09-01 09:15:00| USD|1.0|3.749103|251.386046| 0.84683|2.8468299999999997|
|2025-09-01 09:16:00| USD|1.0|3.749472|251.345014|0.847996|          2.847996|
|2025-09-01 09:17:00| USD|1.0|3.748513|250.944309|0.849207|          2.849207|
|2025-09-01 09:18:00| USD|1.0|3.749391| 251.26516|0.846777|          2.846777|
|2025-09-01 09:19:00| USD|1.0|3.749341| 251.17362|0.843406|          2.843406|
+-------------------+----+---+--------+----------+--------+------------------+
only showing top 20 rows

In [78]:
### Drop the columns
df_pyspark=df_pyspark.drop('Experience After 2 year')

In [79]:
df_pyspark.show()

+-------------------+----+---+--------+----------+--------+------------------+
|          timestamp|base|USD|     SAR|       YER|     EUR|        EUR_plus_2|
+-------------------+----+---+--------+----------+--------+------------------+
|2025-09-01 09:00:00| USD|1.0|3.750305|249.969495|0.849856|          2.849856|
|2025-09-01 09:01:00| USD|1.0|3.749265|250.046174|0.851548|          2.851548|
|2025-09-01 09:02:00| USD|1.0|3.750015|250.246139|0.848127|          2.848127|
|2025-09-01 09:03:00| USD|1.0|3.750956|250.034432|0.845882|          2.845882|
|2025-09-01 09:04:00| USD|1.0|3.749005| 250.00943|0.844497|          2.844497|
|2025-09-01 09:05:00| USD|1.0|3.747703|250.305721|0.846689|          2.846689|
|2025-09-01 09:06:00| USD|1.0| 3.74783|250.157004|0.847113|2.8471130000000002|
|2025-09-01 09:07:00| USD|1.0|3.747514|249.992554|0.848264|          2.848264|
|2025-09-01 09:08:00| USD|1.0|3.747497|250.033015|0.846554|2.8465540000000003|
|2025-09-01 09:09:00| USD|1.0|3.746644|250.201892|0.844874|          2.844874|
|2025-09-01 09:10:00| USD|1.0|3.747524|250.204177|0.845546|          2.845546|
|2025-09-01 09:11:00| USD|1.0|3.748301|250.469969|0.845634|          2.845634|
|2025-09-01 09:12:00| USD|1.0|3.748368|250.641328|0.846457|          2.846457|
|2025-09-01 09:13:00| USD|1.0|3.749495|250.809692|0.846175|          2.846175|
|2025-09-01 09:14:00| USD|1.0|3.749962|250.920515|0.846592|2.8465920000000002|
|2025-09-01 09:15:00| USD|1.0|3.749103|251.386046| 0.84683|2.8468299999999997|
|2025-09-01 09:16:00| USD|1.0|3.749472|251.345014|0.847996|          2.847996|
|2025-09-01 09:17:00| USD|1.0|3.748513|250.944309|0.849207|          2.849207|
|2025-09-01 09:18:00| USD|1.0|3.749391| 251.26516|0.846777|          2.846777|
|2025-09-01 09:19:00| USD|1.0|3.749341| 251.17362|0.843406|          2.843406|
+-------------------+----+---+--------+----------+--------+------------------+
only showing top 20 rows

In [80]:
### Rename the columns
df_pyspark.withColumnRenamed('Name','New Name').show()

+-------------------+----+---+--------+----------+--------+------------------+
|          timestamp|base|USD|     SAR|       YER|     EUR|        EUR_plus_2|
+-------------------+----+---+--------+----------+--------+------------------+
|2025-09-01 09:00:00| USD|1.0|3.750305|249.969495|0.849856|          2.849856|
|2025-09-01 09:01:00| USD|1.0|3.749265|250.046174|0.851548|          2.851548|
|2025-09-01 09:02:00| USD|1.0|3.750015|250.246139|0.848127|          2.848127|
|2025-09-01 09:03:00| USD|1.0|3.750956|250.034432|0.845882|          2.845882|
|2025-09-01 09:04:00| USD|1.0|3.749005| 250.00943|0.844497|          2.844497|
|2025-09-01 09:05:00| USD|1.0|3.747703|250.305721|0.846689|          2.846689|
|2025-09-01 09:06:00| USD|1.0| 3.74783|250.157004|0.847113|2.8471130000000002|
|2025-09-01 09:07:00| USD|1.0|3.747514|249.992554|0.848264|          2.848264|
|2025-09-01 09:08:00| USD|1.0|3.747497|250.033015|0.846554|2.8465540000000003|
|2025-09-01 09:09:00| USD|1.0|3.746644|250.201892|0.844874|          2.844874|
|2025-09-01 09:10:00| USD|1.0|3.747524|250.204177|0.845546|          2.845546|
|2025-09-01 09:11:00| USD|1.0|3.748301|250.469969|0.845634|          2.845634|
|2025-09-01 09:12:00| USD|1.0|3.748368|250.641328|0.846457|          2.846457|
|2025-09-01 09:13:00| USD|1.0|3.749495|250.809692|0.846175|          2.846175|
|2025-09-01 09:14:00| USD|1.0|3.749962|250.920515|0.846592|2.8465920000000002|
|2025-09-01 09:15:00| USD|1.0|3.749103|251.386046| 0.84683|2.8468299999999997|
|2025-09-01 09:16:00| USD|1.0|3.749472|251.345014|0.847996|          2.847996|
|2025-09-01 09:17:00| USD|1.0|3.748513|250.944309|0.849207|          2.849207|
|2025-09-01 09:18:00| USD|1.0|3.749391| 251.26516|0.846777|          2.846777|
|2025-09-01 09:19:00| USD|1.0|3.749341| 251.17362|0.843406|          2.843406|
+-------------------+----+---+--------+----------+--------+------------------+
only showing top 20 rows