### Pyspark GroupBy And Aggregate Functions

In [1]:
from pyspark.sql import SparkSession

In [2]:
spark=SparkSession.builder.appName('YER').getOrCreate()

In [3]:
spark

In [4]:
df_pyspark=spark.read.csv('fx_rates_sample.csv',header=True,inferSchema=True)

In [5]:
df_pyspark.show()

+-------------------+----+---+--------+----------+--------+
|          timestamp|base|USD|     SAR|       YER|     EUR|
+-------------------+----+---+--------+----------+--------+
|2025-09-01 09:00:00| USD|1.0|3.750305|249.969495|0.849856|
|2025-09-01 09:01:00| USD|1.0|3.749265|250.046174|0.851548|
|2025-09-01 09:02:00| USD|1.0|3.750015|250.246139|0.848127|
|2025-09-01 09:03:00| USD|1.0|3.750956|250.034432|0.845882|
|2025-09-01 09:04:00| USD|1.0|3.749005| 250.00943|0.844497|
|2025-09-01 09:05:00| USD|1.0|3.747703|250.305721|0.846689|
|2025-09-01 09:06:00| USD|1.0| 3.74783|250.157004|0.847113|
|2025-09-01 09:07:00| USD|1.0|3.747514|249.992554|0.848264|
|2025-09-01 09:08:00| USD|1.0|3.747497|250.033015|0.846554|
|2025-09-01 09:09:00| USD|1.0|3.746644|250.201892|0.844874|
|2025-09-01 09:10:00| USD|1.0|3.747524|250.204177|0.845546|
|2025-09-01 09:11:00| USD|1.0|3.748301|250.469969|0.845634|
|2025-09-01 09:12:00| USD|1.0|3.748368|250.641328|0.846457|
|2025-09-01 09:13:00| USD|1.0|3.749495|250.809692|0.846175|
|2025-09-01 09:14:00| USD|1.0|3.749962|250.920515|0.846592|
|2025-09-01 09:15:00| USD|1.0|3.749103|251.386046| 0.84683|
|2025-09-01 09:16:00| USD|1.0|3.749472|251.345014|0.847996|
|2025-09-01 09:17:00| USD|1.0|3.748513|250.944309|0.849207|
|2025-09-01 09:18:00| USD|1.0|3.749391| 251.26516|0.846777|
|2025-09-01 09:19:00| USD|1.0|3.749341| 251.17362|0.843406|
+-------------------+----+---+--------+----------+--------+
only showing top 20 rows

In [6]:
df_pyspark.printSchema()

root
 |-- timestamp: timestamp (nullable = true)
 |-- base: string (nullable = true)
 |-- USD: double (nullable = true)
 |-- SAR: double (nullable = true)
 |-- YER: double (nullable = true)
 |-- EUR: double (nullable = true)

In [7]:
## Groupby
### Grouped to find the maximum salary
df_pyspark.groupBy('YER').sum().show()

+----------+--------+--------+----------+--------+
|       YER|sum(USD)|sum(SAR)|  sum(YER)|sum(EUR)|
+----------+--------+--------+----------+--------+
|249.950976|     1.0|3.740207|249.950976|    0.84|
|244.918109|     1.0|3.747181|244.918109|0.849136|
| 248.64662|     1.0|3.740636| 248.64662|0.846003|
| 247.98069|     1.0|3.742048| 247.98069|0.853057|
|250.034432|     1.0|3.750956|250.034432|0.845882|
|249.569796|     1.0|3.740199|249.569796|0.850659|
| 249.30801|     1.0|3.744473| 249.30801|0.843305|
|251.345014|     1.0|3.749472|251.345014|0.847996|
| 249.99013|     1.0|3.745879| 249.99013|0.859617|
|250.357579|     1.0|3.742033|250.357579|0.864181|
|249.229244|     1.0|3.741189|249.229244|0.857841|
|247.766264|     1.0|3.740963|247.766264|0.854857|
| 245.76969|     1.0|3.742188| 245.76969|0.848262|
|250.809692|     1.0|3.749495|250.809692|0.846175|
|248.975599|     1.0|3.754024|248.975599|0.860151|
|249.804186|     1.0|3.745034|249.804186| 0.86022|
|249.458715|     1.0| 3.74383|249.458715|0.841151|
|247.775582|     1.0|3.734267|247.775582|0.845737|
|244.467917|     1.0|3.746675|244.467917|0.856601|
|250.600007|     1.0|3.749661|250.600007|0.847385|
+----------+--------+--------+----------+--------+
only showing top 20 rows

In [8]:
df_pyspark.groupBy('YER').avg().show()

+----------+--------+--------+----------+--------+
|       YER|avg(USD)|avg(SAR)|  avg(YER)|avg(EUR)|
+----------+--------+--------+----------+--------+
|249.950976|     1.0|3.740207|249.950976|    0.84|
|244.918109|     1.0|3.747181|244.918109|0.849136|
| 248.64662|     1.0|3.740636| 248.64662|0.846003|
| 247.98069|     1.0|3.742048| 247.98069|0.853057|
|250.034432|     1.0|3.750956|250.034432|0.845882|
|249.569796|     1.0|3.740199|249.569796|0.850659|
| 249.30801|     1.0|3.744473| 249.30801|0.843305|
|251.345014|     1.0|3.749472|251.345014|0.847996|
| 249.99013|     1.0|3.745879| 249.99013|0.859617|
|250.357579|     1.0|3.742033|250.357579|0.864181|
|249.229244|     1.0|3.741189|249.229244|0.857841|
|247.766264|     1.0|3.740963|247.766264|0.854857|
| 245.76969|     1.0|3.742188| 245.76969|0.848262|
|250.809692|     1.0|3.749495|250.809692|0.846175|
|248.975599|     1.0|3.754024|248.975599|0.860151|
|249.804186|     1.0|3.745034|249.804186| 0.86022|
|249.458715|     1.0| 3.74383|249.458715|0.841151|
|247.775582|     1.0|3.734267|247.775582|0.845737|
|244.467917|     1.0|3.746675|244.467917|0.856601|
|250.600007|     1.0|3.749661|250.600007|0.847385|
+----------+--------+--------+----------+--------+
only showing top 20 rows

In [9]:
### Groupby Departmernts  which gives maximum salary
df_pyspark.groupBy('YER').sum().show()

+----------+--------+--------+----------+--------+
|       YER|sum(USD)|sum(SAR)|  sum(YER)|sum(EUR)|
+----------+--------+--------+----------+--------+
|249.950976|     1.0|3.740207|249.950976|    0.84|
|244.918109|     1.0|3.747181|244.918109|0.849136|
| 248.64662|     1.0|3.740636| 248.64662|0.846003|
| 247.98069|     1.0|3.742048| 247.98069|0.853057|
|250.034432|     1.0|3.750956|250.034432|0.845882|
|249.569796|     1.0|3.740199|249.569796|0.850659|
| 249.30801|     1.0|3.744473| 249.30801|0.843305|
|251.345014|     1.0|3.749472|251.345014|0.847996|
| 249.99013|     1.0|3.745879| 249.99013|0.859617|
|250.357579|     1.0|3.742033|250.357579|0.864181|
|249.229244|     1.0|3.741189|249.229244|0.857841|
|247.766264|     1.0|3.740963|247.766264|0.854857|
| 245.76969|     1.0|3.742188| 245.76969|0.848262|
|250.809692|     1.0|3.749495|250.809692|0.846175|
|248.975599|     1.0|3.754024|248.975599|0.860151|
|249.804186|     1.0|3.745034|249.804186| 0.86022|
|249.458715|     1.0| 3.74383|249.458715|0.841151|
|247.775582|     1.0|3.734267|247.775582|0.845737|
|244.467917|     1.0|3.746675|244.467917|0.856601|
|250.600007|     1.0|3.749661|250.600007|0.847385|
+----------+--------+--------+----------+--------+
only showing top 20 rows

In [10]:
df_pyspark.groupBy('YER').mean().show()

+----------+--------+--------+----------+--------+
|       YER|avg(USD)|avg(SAR)|  avg(YER)|avg(EUR)|
+----------+--------+--------+----------+--------+
|249.950976|     1.0|3.740207|249.950976|    0.84|
|244.918109|     1.0|3.747181|244.918109|0.849136|
| 248.64662|     1.0|3.740636| 248.64662|0.846003|
| 247.98069|     1.0|3.742048| 247.98069|0.853057|
|250.034432|     1.0|3.750956|250.034432|0.845882|
|249.569796|     1.0|3.740199|249.569796|0.850659|
| 249.30801|     1.0|3.744473| 249.30801|0.843305|
|251.345014|     1.0|3.749472|251.345014|0.847996|
| 249.99013|     1.0|3.745879| 249.99013|0.859617|
|250.357579|     1.0|3.742033|250.357579|0.864181|
|249.229244|     1.0|3.741189|249.229244|0.857841|
|247.766264|     1.0|3.740963|247.766264|0.854857|
| 245.76969|     1.0|3.742188| 245.76969|0.848262|
|250.809692|     1.0|3.749495|250.809692|0.846175|
|248.975599|     1.0|3.754024|248.975599|0.860151|
|249.804186|     1.0|3.745034|249.804186| 0.86022|
|249.458715|     1.0| 3.74383|249.458715|0.841151|
|247.775582|     1.0|3.734267|247.775582|0.845737|
|244.467917|     1.0|3.746675|244.467917|0.856601|
|250.600007|     1.0|3.749661|250.600007|0.847385|
+----------+--------+--------+----------+--------+
only showing top 20 rows

In [11]:
df_pyspark.groupBy('YER').count().show()

+----------+-----+
|       YER|count|
+----------+-----+
|249.950976|    1|
|244.918109|    1|
| 248.64662|    1|
| 247.98069|    1|
|250.034432|    1|
|249.569796|    1|
| 249.30801|    1|
|251.345014|    1|
| 249.99013|    1|
|250.357579|    1|
|249.229244|    1|
|247.766264|    1|
| 245.76969|    1|
|250.809692|    1|
|248.975599|    1|
|249.804186|    1|
|249.458715|    1|
|247.775582|    1|
|244.467917|    1|
|250.600007|    1|
+----------+-----+
only showing top 20 rows

In [12]:
df_pyspark.agg({'YER':'sum'}).show()

+-----------------+
|         sum(YER)|
+-----------------+
|89441.72000200002|
+-----------------+